---
- name: Install Tomcat
  hosts: all
  become: true
  tasks:
    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.95/src/apache-tomcat-9.0.95-src.tar.gz"
        dest: /home/ubuntu/apache-tomcat-9.0.95-src.tar.gz

    - name: Untar the package
      shell: tar -xvzf /home/ubuntu/apache-tomcat-9.0.95-src.tar.gz -C /home/ubuntu

    - name: Rename the Tomcat directory
      command: mv /home/ubuntu/apache-tomcat-9.0.95 /home/ubuntu/tomcat

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Copy the context.xml
      template:
        src: context.xml
        dest: /home/ubuntu/tomcat/webapps/manager/META-INF/context.xml

    - name: Copy tomcat-users.xml
      template:
        src: tomcat-users.xml
        dest: /home/ubuntu/tomcat/conf/tomcat-users.xml

    - name: Start Tomcat
      shell: nohup /home/ubuntu/tomcat/bin/startup.sh &




-xvzf options:
x: Extract files.
v: Verbose mode (show the files being extracted).
z: Use gzip compression.
f: Specifies the file to extract.
-C: Extracts the archive to the specified directory (/home/ubuntu).

nohup: Ensures the process continues running even if the terminal session is closed.
startup.sh: This is Tomcat's startup script.
&: Runs the command in the background.
